// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  // As funções de servidor do SGM rodam dentro deste app (src/lib/edge/fns),
  // expostas em /api/public/edge/<nome>. Mantemos a mesma API de chamada.
  const invoke = async (name: string, options: any = {}) => {
    try {
      const headers = new Headers(options?.headers ?? {});
      headers.set('apikey', SUPABASE_PUBLISHABLE_KEY);
      if (!headers.has('Authorization')) {
        const { data } = await client.auth.getSession();
        const token = data.session?.access_token;
        headers.set('Authorization', `Bearer ${token ?? SUPABASE_PUBLISHABLE_KEY}`);
      }

      let body: BodyInit | undefined;
      if (options?.body instanceof FormData || typeof options?.body === 'string') {
        body = options.body;
      } else if (options?.body !== undefined) {
        headers.set('Content-Type', 'application/json');
        body = JSON.stringify(options.body);
      }

      const method = options?.method ?? (body !== undefined ? 'POST' : 'GET');
      const base =
        typeof window !== 'undefined'
          ? window.location.origin
          : (process.env['APP_ORIGIN'] ?? '');
      const response = await fetch(`${base}/api/public/edge/${name}`, {
        method,
        headers,
        ...(body !== undefined ? { body } : {}),
      });

      const texto = await response.text();
      let data: any = null;
      try {
        data = texto ? JSON.parse(texto) : null;
      } catch {
        data = texto;
      }

      if (!response.ok) {
        const mensagem =
          (data && (data.error || data.message)) || `Erro ${response.status} em ${name}`;
        return { data, error: Object.assign(new Error(mensagem), { status: response.status }) };
      }
      return { data, error: null };
    } catch (error) {
      return { data: null, error: error instanceof Error ? error : new Error(String(error)) };
    }
  };

  (client.functions as any).invoke = invoke;

  return client;
}




let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

